controllers/FolloweesController.php
<?php

namespace app\controllers;

use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\Followee;
use yii\data\ActiveDataProvider;
use Yii;

class FolloweesController extends \yii\web\Controller
{

  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['index'],
        'rules' => [
          [
            'actions' => ['index'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'index' => ['get'],
        ],
      ],
    ];
  }

  public function actions()
  {
    return [
      'error' => [
        'class' => 'yii\web\ErrorAction',
      ],
    ];
  }

  public function actionIndex()
  {
    $query = Followee::getActiveFolloweesQuery(Yii::$app->user->id);
    $dataProvider = new ActiveDataProvider([
      'query' => $query,
      'pagination' => [
        'pageSize' => Yii::$app->params['pagination']['pageSize'],
      ],
    ]);

    return $this->render('index', [
      'dataProvider' => $dataProvider
    ]);
  }
}

controllers/LogController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Log;
use app\models\LogSearch;
use app\models\Blog;
use yii\web\Controller;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class LogController extends Controller
{

  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['index'],
        'rules' => [
          [
            'actions' => ['index'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'index' => ['get'],
        ],
      ],
    ];
  }

  /**
   * Lists all Log models.
   * @return mixed
   */
  public function actionIndex()
  {
    $searchModel = new LogSearch(['userId' => Yii::$app->user->id]);
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    $blogs = ArrayHelper::map(Blog::queryForIndex(Yii::$app->user->id)->all(), 'id', 'blogname');
    $actionTitles = Log::getActionTitles();

    return $this->render('index', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
      'blogs' => $blogs,
      'actionTitles' => $actionTitles,
    ]);
  }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use app\models\User;
use app\models\Blog;
use app\models\update\DataUpdate;
use app\models\Tumblr;

class SiteController extends Controller
{

  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['logout', 'update', 'access'],
        'rules' => [
          [
            'actions' => ['logout', 'update'],
            'allow' => true,
            'roles' => ['@'],
          ],
          [
            'actions' => ['access', 'login'],
            'allow' => true,
            'roles' => ['?'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'logout' => ['post'],
        ],
      ],
    ];
  }

  public function actions()
  {
    return [
      'error' => [
        'class' => 'yii\web\ErrorAction',
      ],
    ];
  }

  public function actionIndex()
  {
    if (Yii::$app->user->isGuest) {
      return $this->render('index');
    } else {
      $blogListQuery = Blog::queryForIndex(Yii::$app->user->id);
      $dataProvider = new ActiveDataProvider([
        'query' => $blogListQuery,
        'pagination' => false,
      ]);
      return $this->render('index', ['dataProvider' => $dataProvider]);
    }
  }

  public function actionLogin()
  {
    if (!\Yii::$app->user->isGuest) {
      return $this->goHome();
    }

    return $this->redirect(Tumblr::oauthStartLogin());
  }

  public function actionAccess()
  {
    if (!\Yii::$app->user->isGuest) {
      return $this->goHome();
    }

    $accessToken = Tumblr::oauthFinishLogin();

    $tumblrResponse = Tumblr::getUserInfo();

    $user = User::saveSession($tumblrResponse, $accessToken);
    Yii::$app->user->login($user);
    Blog::resetBlogs($user->id);
    Blog::setActiveBlogs($user->id, $tumblrResponse['blogs']);

    return $this->goHome();
  }

  public function actionLogout()
  {
    Yii::$app->user->logout();

    return $this->goHome();
  }

  public function actionUpdate()
  {
    $oauthClient = Yii::$app->oauth;
    $oauthClient->setAccessToken(Yii::$app->user->identity->getAccessTokenBlob());

    $dataUpdate = new DataUpdate();
    $dataUpdate->update(Yii::$app->user->id);

    Yii::$app->session->setFlash("alert", "Data has been updated!");
    return $this->goHome();
  }
}

views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\bootstrap\Alert;
use yii\bootstrap\Modal;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
  <head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
  </head>
  <body>
      <?php $this->beginBody() ?>

    <div class="wrap">
        <?php
        NavBar::begin([
          'brandLabel' => 'Tumblr Follower Activity Watcher',
          'brandUrl' => Yii::$app->homeUrl,
          'options' => [
            'class' => 'navbar-default',
          ],
        ]);
        echo Nav::widget([
          'options' => ['class' => 'navbar-nav navbar-right'],
          'items' => Yii::$app->user->isGuest ?
          [
            [
              'label' => 'Login',
              'url' => ['/site/login'],
            ],
          ] :
          [
            [
              'label' => 'Update data',
              'url' => ['/site/update'],
            ],
            [
              'label' => 'Blogs',
              'url' => ['/site/index'],
            ],
            [
              'label' => 'Followees',
              'url' => ['/followees/index'],
            ],
            [
              'label' => 'History',
              'url' => ['/log/index'],
            ],
            [
              'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
              'url' => ['/site/logout'],
              'linkOptions' => ['data-method' => 'post'],
            ],
          ],
        ]);
        NavBar::end();
        ?>

      <?php
      Modal::begin([
        'header' => '<h2>Blog info</h2>',
        'id' => 'blogInfoModal',
      ]);
      ?>
      <div id="modalContent">

      </div>
      <?php Modal::end(); ?>

      <div class="container">
        <?php
        if (Yii::$app->session->hasFlash('alert')) {
          echo Alert::widget([
            'options' => [
              'class' => 'alert-info',
            ],
            'body' => Yii::$app->session->getFlash('alert')
          ]);
        }
        ?>
        <?= $content ?>
      </div>
    </div>

    <?php $this->endBody() ?>
  </body>
</html>
<?php $this->endPage() ?>