models/Log.php
<?php

namespace app\models;

use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "log".
 *
 * @property integer $id
 * @property integer $userId
 * @property string $userBlog
 * @property string $blogName
 * @property string $blogUrl
 * @property integer $action
 * @property string $date
 */
class Log extends \yii\db\ActiveRecord
{

  const ACTION_ADDED_FOLLOWEE = 1;
  const ACTION_REMOVED_FOLLOWEE = 2;
  const ACTION_ACQUIRED_FOLLOWER = 3;
  const ACTION_LOST_FOLLOWER = 4;

  /**
   * @inheritdoc
   */
  public static function tableName()
  {
    return 'log';
  }

  /**
   * @inheritdoc
   */
  public function behaviors()
  {
    return array_merge(parent::behaviors(), [
      [
        'class' => TimestampBehavior::className(),
        'createdAtAttribute' => 'date',
        'updatedAtAttribute' => null,
        'value' => function() {
          return date('U');
        },
      ],
    ]);
  }

  /**
   * @inheritdoc
   */
  public function rules()
  {
    return [
      [['userId', 'blogName', 'blogUrl', 'action'], 'required'],
      [['userBlog', 'userId', 'action'], 'integer'],
      [['blogName', 'blogUrl'], 'string', 'max' => 100],
      ['date', 'string'],
      ['userBlog', 'required', 'when' => function($model) {
        return in_array($model->action, [self::ACTION_ACQUIRED_FOLLOWER, self::ACTION_LOST_FOLLOWER]);
      }],
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'userId' => 'User ID',
      'userBlog' => 'User Blog',
      'blogName' => 'Blog Name',
      'blogUrl' => 'Blog Url',
      'action' => 'Action',
      'date' => 'Date',
    ];
  }

  public static function getActionTitles()
  {
    return [
      Log::ACTION_ADDED_FOLLOWEE => 'Added followee',
      Log::ACTION_REMOVED_FOLLOWEE => 'Removed followee',
      Log::ACTION_ACQUIRED_FOLLOWER => 'Acquired follower',
      Log::ACTION_LOST_FOLLOWER => 'Lost follower',
    ];
  }

  public function getBlog()
  {
    return $this->hasOne(Blog::className(), ['id' => 'userBlog', 'userId' => 'userId']);
  }
}

controllers/BlogInfoController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\Tumblr;
use app\models\BlogInfo;

class BlogInfoController extends Controller
{

  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['index'],
        'rules' => [
          [
            'actions' => ['index'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'index' => ['get'],
        ],
      ],
    ];
  }

  public function actionIndex($blog)
  {
    $oauthClient = Yii::$app->oauth;
    $oauthClient->setAccessToken(Yii::$app->user->identity->getAccessTokenBlob());

    $tumblrData = Tumblr::getBlogInfo($blog);
    $blogInfo = new BlogInfo();
    $blogInfo->setAttributes($tumblrData);

    if (Yii::$app->getRequest()->isAjax) {
      return $this->renderPartial('index', ['blogInfo' => $blogInfo]);
    } else {
      return $this->render('index', ['blogInfo' => $blogInfo]);
    }
  }
}

controllers/FollowersController.php
<?php

namespace app\controllers;

use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use Yii;
use app\models\Follower;
use app\models\Blog;

class FollowersController extends \yii\web\Controller
{

  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['index'],
        'rules' => [
          [
            'actions' => ['index'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'index' => ['get'],
        ],
      ],
    ];
  }

  public function actions()
  {
    return [
      'error' => [
        'class' => 'yii\web\ErrorAction',
      ],
    ];
  }

  public function actionIndex($blogId)
  {
    if (empty($blogId)) {
      return $this->goHome();
    }
    $blogData = Blog::getByUserAndId(Yii::$app->user->id, $blogId);
    if (empty($blogData)) {
      return $this->goHome();
    }

    $query = Follower::getActiveFollowersQuery(Yii::$app->user->id, $blogId);
    $dataProvider = new ActiveDataProvider([
      'query' => $query,
      'pagination' => [
        'pageSize' => Yii::$app->params['pagination']['pageSize'],
      ],
    ]);

    return $this->render('index', [
      'dataProvider' => $dataProvider,
      'blogData' => $blogData,
    ]);
  }
}

controllers/LogController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Log;
use app\models\LogSearch;
use app\models\Blog;
use yii\web\Controller;
use yii\helpers\ArrayHelper;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class LogController extends Controller
{

  public function behaviors()
  {
    return [
      'access' => [
        'class' => AccessControl::className(),
        'only' => ['index'],
        'rules' => [
          [
            'actions' => ['index'],
            'allow' => true,
            'roles' => ['@'],
          ],
        ],
      ],
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'index' => ['get'],
        ],
      ],
    ];
  }

  /**
   * Lists all Log models.
   * @return mixed
   */
  public function actionIndex()
  {
    $searchModel = new LogSearch(['userId' => Yii::$app->user->id]);
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    $blogs = ArrayHelper::map(Blog::queryForIndex(Yii::$app->user->id)->all(), 'id', 'blogname');
    $actionTitles = Log::getActionTitles();

    return $this->render('index', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
      'blogs' => $blogs,
      'actionTitles' => $actionTitles,
    ]);
  }
}

views/log/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\daterange\DateRangePicker;

\app\assets\BlogInfoAsset::register($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\LogSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'History - Tumblr Follower Activity Watcher';
?>
<div class="log-index">

  <h1>History</h1>
  <?php Pjax::begin(['id' => 'LogPjax']); ?>
  <?=
  GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
      [
        'attribute' => 'userBlog',
        'format' => 'raw',
        'value' => function ($model) {
          if ($model->blog) {
            $imgUrl = "https://api.tumblr.com/v2/blog/{$model->blog->blogname}.tumblr.com/avatar/24";
            $img = Html::img($imgUrl);
            return Html::a($img . ' ' . $model->blog->blogname, Url::to(['followers/index', 'blogId' => $model->userBlog]), [
              'data-pjax' => 0,
            ]);
          }
          return '';
        },
        'filter' => $blogs,
      ],
      [
        'attribute' => 'blogName',
        'format' => 'raw',
        'value' => function($model) {
          $imgUrl = "https://api.tumblr.com/v2/blog/{$model->blogName}.tumblr.com/avatar/24";
          $img = Html::img($imgUrl);
          return Html::a($img . ' ' . Html::encode($model->blogName), ['blog-info/index', 'blog' => $model->blogName], [
            'data-blog' => $model->blogName,
            'class' => 'blog-info'
          ]);
        },
      ],
      'blogUrl:url',
      [
        'attribute' => 'action',
        'value' => function ($model) use ($actionTitles) {
          return $actionTitles[$model->action];
        },
        'filter' => $actionTitles,
      ],
      [
        'attribute' => 'date',
        'format' => 'datetime',
        'filter' => DateRangePicker::widget([
          'model' => $searchModel,
          'attribute' => 'date',
          'convertFormat' => true,
          'useWithAddon' => false,
          'pluginOptions' => [
            'locale' => [
              'format' => 'd M Y',
              'separator' => Yii::$app->params['dateSeparator'],
            ],
            'opens' => 'left'
          ]
        ])
      ]
    ],
  ]);
  ?>
  <?php Pjax::end(); ?>
</div>